import Header from "@/src/components/navbar/Navbar";
import "@/public/styles/global.css";
import Footer from "@/src/components/footer/Footer";
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
        {/* <Footer /> */}
      </body>
    </html>
  );
}
